"""Human-readable proposal document (owner's standing requirement), generated from committed data.

Sources: the latest committed Concorde run snapshot (reports/runs/*.json), validation_status.yaml,
open_items.yaml, the candidate-core set and the known-limits register. ``python -m ssbj proposal``
writes reports/proposal.md; tests/test_docs.py checks the committed file is in sync.
"""
from __future__ import annotations

import json
from pathlib import Path

import yaml

HERE = Path(__file__).parent


def _latest_run() -> dict:
    runs = sorted((HERE / "runs").glob("concorde_*.json"))
    return json.loads(runs[-1].read_text())


def _fmt(v, nd=0):
    return "-" if v is None else f"{v:,.{nd}f}"


def render() -> str:
    from ssbj.docs.register import GEOMETRY, MODULES

    run = _latest_run()
    status = yaml.safe_load((HERE / "validation_status.yaml").read_text())
    items = yaml.safe_load((HERE / "open_items.yaml").read_text())
    nom, comp = run["nominal"], run["comparison"]
    n_checks = sum(len(c["checks"]) for c in status["cases"])
    n_fail = sum(ch["result"] == "fail" for c in status["cases"] for ch in c["checks"])

    L = ["# Mach 1.5 transatlantic business jet: proposal (working draft)", "",
         "Generated by `python -m ssbj proposal` from committed pipeline data; do not edit by hand.", "",
         f"Status: **concept stage, roadmap item 1 complete.** Evidence base: Concorde run `{run['run_id']}` "
         f"(code `{run['code_version'].get('git_sha', '?')[:10]}`), {len(status['cases'])} validation cases, "
         f"{n_checks} checks, **{n_fail} failing**.", "",
         "## 1. What is proposed", "",
         "- A Mach 1.5 business jet sized for transatlantic city pairs, designed with an open, "
         "reproducible pipeline in which every number carries a source and an error bar.",
         "- Propulsion: a **bought gas-generator core** (HP compressor, combustor, HP turbine) with an "
         "in-house fan, LP turbine, forced mixer, nozzle and intake (D-024). Candidate cores, in order "
         "of technical fit: CFM56 / F101 '1/9' core (Affinity precedent, US export control), PW800 "
         "(GTF core), RR Pearl / BR700 (European, high HPC pressure ratio). Details: "
         "`ssbj/disciplines/propulsion/cores/CANDIDATES.md`.",
         "- The aircraft itself is not yet sized (roadmap item 5). This draft states what the pipeline "
         "can currently predict and how well that has been checked.", "",
         "## 2. Can the pipeline predict a supersonic transport? (Concorde, blind reproduction)", "",
         "| Quantity | Published | Model nominal | Model 95 % interval | Result |", "|---|---|---|---|---|"]
    for g in comp["gates"]:
        L.append(f"| {g['quantity']} | {_fmt(g['value'])} {g['unit']} | {_fmt(g['model_nominal'])} | "
                 f"{_fmt(g['model_p2.5'])}-{_fmt(g['model_p97.5'])} | "
                 f"{'**pass**' if g['inside_95'] else '**fail**'} (gate) |")
    for d in comp["diagnostics"]:
        if d.get("model_nominal") is None:
            continue
        pub = d["range"] and f"{d['range'][0]:,}-{d['range'][1]:,}" or _fmt(d["value"], 3 if d["value"] < 10 else 0)
        nd = 3 if abs(d["model_nominal"]) < 10 else 0
        lo, hi = d.get("model_p2.5"), d.get("model_p97.5")
        unit = "" if d["unit"] in ("-", None) else f" {d['unit']}"
        band = "-" if lo is None else f"{_fmt(lo, nd)}-{_fmt(hi, nd)}"
        L.append(f"| {d['id'].replace('_', ' ')} | {pub}{unit} | {_fmt(d['model_nominal'], nd)} | {band} | diagnostic |")
    L += ["", f"Monte Carlo: {run['monte_carlo']['n_samples']} samples; intervals are conditional on the "
          "sample being able to fly the mission (see the run report).", "",
          f"Nominal: OEW {_fmt(nom.get('oew_kg'))} kg, cruise L/D {nom.get('ld_cruise', 0):.2f}, cruise TSFC "
          f"{nom.get('tsfc_cruise_per_h', 0):.3f} /h, transonic thrust margin "
          f"{nom.get('transonic_thrust_margin', 0):.2f}.", "",
          "## 3. Component validation", ""]
    for c in status["cases"]:
        L += [f"### {c['name']}", "", f"{c['kind']}; test `{c['test']}`.", "",
              "| Check | Reference | Model | Tolerance | Result |", "|---|---|---|---|---|"]
        L += [f"| {ch['quantity']} | {ch['published']} | {ch['model']} | {ch['tol']} | "
              f"{'pass' if ch['result'] == 'pass' else '**FAIL**'} |" for ch in c["checks"]]
        L.append("")
    L += ["## 4. Remaining deficiencies", "",
          "### Model and evidence gaps", ""]
    L += [f"- {x}" for x in items["deficiencies"]]
    L += ["", "### Decisions needed from the owner", ""]
    L += [f"- {x}" for x in items["decisions"]]
    L += ["", "### Known limits of the methods (from the register)", "", "Geometry:", ""]
    L += [f"- {x}" for x in GEOMETRY]
    for name, mod in MODULES:
        L += ["", f"{name}:", ""] + [f"- {x}" for x in mod.LIMITS]
    L += ["", "## 5. Next steps", "",
          "Roadmap item 2: Mach 1.5-class validation gated at component level (L/D, SFC, OEW, segment "
          "fuel fractions, interval width). Then calibration on non-test aircraft (item 3). See "
          "`ssbj/reports/roadmap.md` and `ssbj/reports/decision_log.md`.", ""]
    return "\n".join(L)


def write(out: Path | None = None) -> Path:
    out = out or HERE / "proposal.md"
    out.write_text(render())
    return out
