"""Known-limits register, rendered from the LIMITS and UNCERTAINTIES each module declares.

The register is generated so it cannot drift from the code; tests/test_docs.py
checks that the committed known_limits.md matches render().
"""
from __future__ import annotations

from ssbj.disciplines.aero import polar
from ssbj.disciplines.mission import analysis
from ssbj.disciplines.propulsion import deck
from ssbj.disciplines.weights import raymer_transport

MODULES = [("Aerodynamics", polar), ("Propulsion", deck), ("Weights", raymer_transport),
           ("Mission", analysis)]

GEOMETRY = [
    "Thin-wing area-rule slicing: wing and fin thickness integrated along the cut line in their own "
    "planes (no dihedral, twist or camber).",
    "Nacelles are rectangular shells with the capture streamtube removed and cosine ramps at both "
    "ends; boundary-layer diverters and intake ramps are not modelled.",
    "Fuselage wetted area includes the wing-junction strip that OpenVSP removes (about 6 % on Concorde): "
    "conservative.",
    "Wing fuel volume (10-75 % chord) is a usable-volume proxy; fuselage and trim tanks are not counted.",
]


def render() -> str:
    L = ["# Known limits register", "",
         "Generated by `python -m ssbj limits` from the modules; do not edit by hand.", "",
         "Error bars are 1-sigma relative factors sampled by the Monte Carlo. A module used outside "
         "the conditions below should have its sigma widened, and its run warnings say when that "
         "happens.", "",
         "## Geometry", ""]
    L += [f"- {x}" for x in GEOMETRY]
    for name, mod in MODULES:
        L += ["", f"## {name}", "", "Not trusted when:", ""]
        L += [f"- {x}" for x in mod.LIMITS]
        L += ["", "| Error factor | 1-sigma | Basis |", "|---|---|---|"]
        L += [f"| `{u.name}` | {u.sigma_rel:.0%} | {u.basis} |" for u in mod.UNCERTAINTIES]
    return "\n".join(L) + "\n"
